// The conformance suite. Each directory under fixtures/ is a miniature
// repository; this runs the real CLI against it and compares the result with
// its expected.json. See fixtures/README.MD for the comparison rules.

import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
} from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { statSync } from "node:fs";
import { open } from "../src/repository.js";
import { isOwnership } from "../src/match.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..", "..");
const cli = path.join(root, "dist", "src", "cli.js");
const fixturesDir = path.join(root, "fixtures");

interface Expected {
  exit?: number;
  error?: string | Record<string, unknown>;
  issues?: unknown[];
  /** Extra arguments for the lint run — scoping is the case that needs them. */
  args?: string[];
  /**
   * Warnings the lint run must emit, in order. The partial-run line is the only
   * place a child espalier that was visited and found nothing differs from one
   * that was never visited, so a fixture about scoping has to assert it.
   */
  warnings?: string[];
  explain?: Record<string, { exit: number; object: unknown; human?: string }>;
  ownership?: Record<string, string | null>;
  stderr?: string[];
  /** A file holding the exact `--format human` stdout of the same lint run. */
  human?: string;
  /** Environment the lint run is given, on top of the harness's own. */
  env?: Record<string, string>;
  again?: Rerun;
  build?: WriteRun;
  init?: WriteRun;
  adopt?: WriteRun;
}

/** A command that writes: `build` and `init` are asserted the same way. */
interface WriteRun {
  exit: number;
  args?: string[];
  report?: unknown[];
  /**
   * Warning messages the run must emit, in order. A warning is advice about
   * what was written rather than part of the record of it, so it is compared
   * separately from `report`.
   */
  warnings?: string[];
  /** A file holding the exact `--format human` stdout of the same run. */
  human?: string;
}

/**
 * A second `lint` over the same copy, after the tree or the environment
 * changed. Only an incremental run has anything to say here: everything else
 * espalier does is settled by the first run, and a fixture that reran without
 * a cache would assert that the same input gives the same answer.
 */
interface Rerun {
  /** A directory copied over the copy: files to add, or to replace. */
  apply?: string;
  /** Paths removed from the copy. */
  delete?: string[];
  /** Environment for this run only. */
  env?: Record<string, string>;
  exit: number;
  issues?: unknown[];
}

/** Scaffolding for the harness, never part of the repository under test. */
const SCAFFOLDING = new Set([
  "FIXTURE.MD",
  "expected.json",
  "expected-build",
  "expected-init",
  "expected-adopt",
  "human",
  "after",
]);

const PROVENANCE = "<!-- generated by espalier";

/**
 * Compares `actual` against `expected`, ignoring anything `expected` does not
 * mention. The rule applies at every depth, so an expected `metadata` naming
 * two keys asserts nothing about a third. Arrays are compared in order and by
 * length — a declared list is sorted, so its order is meaningful.
 *
 * Returns a description of the first mismatch, or null when it matches.
 */
function mismatch(actual: unknown, expected: unknown, at: string): string | null {
  if (Array.isArray(expected)) {
    if (!Array.isArray(actual)) {
      return `${at}: expected an array, got ${JSON.stringify(actual)}`;
    }
    if (actual.length !== expected.length) {
      return `${at}: expected ${expected.length} entries, got ${actual.length}`;
    }
    for (const [i, value] of expected.entries()) {
      const found = mismatch(actual[i], value, `${at}[${i}]`);
      if (found) return found;
    }
    return null;
  }

  if (expected !== null && typeof expected === "object") {
    if (actual === null || typeof actual !== "object" || Array.isArray(actual)) {
      return `${at}: expected an object, got ${JSON.stringify(actual)}`;
    }
    const target = actual as Record<string, unknown>;
    for (const [key, value] of Object.entries(expected)) {
      if (!(key in target)) return `${at}.${key}: absent`;
      const found = mismatch(target[key], value, `${at}.${key}`);
      if (found) return found;
    }
    return null;
  }

  if (actual !== expected) {
    return `${at}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`;
  }
  return null;
}

/** Every file under `dir`, repository-relative and sorted. */
function walk(dir: string, prefix = ""): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    const at = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) found.push(...walk(path.join(dir, entry.name), at));
    else found.push(at);
  }
  return found;
}

/**
 * Every path under `dir` as the tool would see it: links followed, a link onto
 * a directory containing it refused. Separate from `walk` above, which compares
 * generated trees and has no links to meet — this one is the independent list
 * the agreement sweep asks about, so it must not be built from the thing it is
 * checking.
 */
function walkFollowing(dir: string, prefix = "", ancestors?: Set<string>): string[] {
  const stats = statSync(dir);
  const seen = ancestors ?? new Set<string>([`${stats.dev}:${stats.ino}`]);
  const found: string[] = [];

  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    const at = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    const absolute = path.join(dir, entry.name);
    let resolved;
    try {
      resolved = statSync(absolute);
    } catch {
      // A link pointing nowhere. The run it is about fails, and a fixture
      // asserting a failure is not swept.
      continue;
    }
    if (!resolved.isDirectory()) {
      if (resolved.isFile()) found.push(at);
      continue;
    }
    const id = `${resolved.dev}:${resolved.ino}`;
    if (seen.has(id)) continue;
    seen.add(id);
    found.push(...walkFollowing(absolute, at, seen));
    seen.delete(id);
  }
  return found;
}

/**
 * Issues are compared as an unordered multiset: the runner promises no order,
 * but two identical issues are not one issue. Matching is greedy, which is
 * sufficient while no fixture expects two issues where one expectation is a
 * strict refinement of another.
 */
function compareIssues(actual: unknown[], expected: unknown[]): string[] {
  const unmatched = [...actual];
  const problems: string[] = [];

  for (const [i, want] of expected.entries()) {
    const at = unmatched.findIndex((got) => mismatch(got, want, "issue") === null);
    if (at === -1) {
      problems.push(`no issue matched expected[${i}]: ${JSON.stringify(want)}`);
    } else {
      unmatched.splice(at, 1);
    }
  }

  for (const extra of unmatched) {
    problems.push(`unexpected issue: ${JSON.stringify(extra)}`);
  }
  return problems;
}

function run(cwd: string, args: string[], env?: Record<string, string>) {
  const result = spawnSync(process.execPath, [cli, ...args], {
    cwd,
    encoding: "utf8",
    env: env === undefined ? process.env : { ...process.env, ...env },
  });
  if (result.error) throw result.error;
  return {
    status: result.status ?? -1,
    stdout: result.stdout,
    stderr: result.stderr,
  };
}

function parseLines(stdout: string, what: string): Record<string, unknown>[] {
  return stdout
    .split("\n")
    .filter((line) => line.trim() !== "")
    .map((line, i) => {
      try {
        return JSON.parse(line) as Record<string, unknown>;
      } catch {
        throw new Error(`${what}: line ${i + 1} is not JSON: ${line}`);
      }
    });
}

const fixtures = readdirSync(fixturesDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

/**
 * Runs `build` against a throwaway copy — fixtures are inputs and are never
 * written into — and compares what it left behind.
 *
 * Every copy here is `verbatimSymlinks`. Node otherwise resolves a relative
 * link against the destination and writes an absolute one, which would point a
 * fixture's link back at the fixture it was copied from: a symlink fixture
 * would then pass while testing the original tree, and a cycle would leave the
 * copy entirely.
 *
 * With an `expected-build/`, the comparison is byte-for-byte and both ways:
 * every golden file must exist with exactly those bytes, and every generated
 * file the run produced must be one of them. Without one, the assertion is
 * that the tree is untouched, which is what `--check` promises and what a run
 * that halts owes the user.
 */
function checkWrites(dir: string, command: string, expected: WriteRun): void {
  const golden = path.join(dir, `expected-${command}`);
  // Copied into a directory named for the fixture, not into the temporary
  // directory itself. `init` writes the directory's own name into the config,
  // and a random one would be a golden nothing could pin.
  const scratch = path.join(mkdtempSync(path.join(os.tmpdir(), "espalier-fixture-")), path.basename(dir));
  mkdirSync(scratch);

  try {
    cpSync(dir, scratch, {
      recursive: true,
      verbatimSymlinks: true,
      filter: (source) => !SCAFFOLDING.has(path.relative(dir, source)),
    });

    // The report is what a person reads, and its column widths are fixed by
    // the command's page. Run it on its own copy first: the jsonl run below
    // needs the tree as it started.
    if (expected.human !== undefined) {
      const spare = path.join(mkdtempSync(path.join(os.tmpdir(), "espalier-human-")), path.basename(dir));
      try {
        cpSync(scratch, spare, { recursive: true, verbatimSymlinks: true });
        const shown = run(spare, [command, ...(expected.args ?? [])]);
        assert.equal(
          shown.stdout,
          readFileSync(path.join(dir, expected.human), "utf8"),
          `${command} --format human differs from ${expected.human}`,
        );
      } finally {
        rmSync(path.dirname(spare), { recursive: true, force: true });
      }
    }
    const before = new Map(
      walk(scratch).map((at) => [at, readFileSync(path.join(scratch, at), "utf8")]),
    );

    const build = run(scratch, [command, "--format", "jsonl", ...(expected.args ?? [])]);
    assert.equal(
      build.status,
      expected.exit,
      `exit code\nstdout:\n${build.stdout}\nstderr:\n${build.stderr}`,
    );

    const lines = parseLines(build.stdout, command);
    const warnings = lines.filter((line) => line["kind"] === "warning");
    assert.deepEqual(
      warnings.map((line) => line["message"]),
      expected.warnings ?? [],
      `${command} warnings`,
    );

    const problems = compareIssues(
      lines.filter((line) => line["kind"] !== "warning"),
      expected.report ?? [],
    );
    assert.ok(problems.length === 0, problems.join("\n"));

    const after = new Map(
      walk(scratch).map((at) => [at, readFileSync(path.join(scratch, at), "utf8")]),
    );

    if (!existsSync(golden)) {
      assert.deepEqual([...after].sort(), [...before].sort(), `${command} changed the tree`);
      return;
    }

    for (const at of walk(golden)) {
      const want = readFileSync(path.join(golden, at), "utf8");
      assert.equal(after.get(at), want, `${at} differs from expected-${command}/${at}`);
    }

    const wanted = new Set(walk(golden));
    for (const [at, content] of after) {
      // Produced means generated documentation, or any file this run created.
      // `build` is identified by the marker; `init` writes plain files.
      if ((content.startsWith(PROVENANCE) || !before.has(at)) && !wanted.has(at)) {
        assert.fail(`${at} was produced but is not in expected-${command}/`);
      }
    }
  } finally {
    rmSync(path.dirname(scratch), { recursive: true, force: true });
  }
}

/**
 * Every file in the fixture, and the rule that owns it. Exhaustive, unlike
 * every other assertion here: a clean run says nothing about who owns what, and
 * a matcher handing files to the wrong rule would still exit 0 with no issues.
 */
/** What `explain` answered about one path, reduced to what is compared. */
interface Answer {
  rule: string | null;
  ignoredBy: string | null;
}

/** The directories holding the given paths, including the root, sorted. */
function directoriesOf(paths: string[]): string[] {
  const found = new Set<string>([""]);
  for (const at of paths) {
    const segments = at.split("/");
    for (let depth = 1; depth < segments.length; depth += 1) {
      found.add(segments.slice(0, depth).join("/"));
    }
  }
  return [...found].sort();
}

/**
 * The paths a fixture is about: everything under it except the harness's own
 * scaffolding, the config, and the espalier root — which is invisible to
 * matching, so listing its modules would be a column of nulls.
 */
function subject(dir: string): string[] {
  const config = readFileSync(path.join(dir, "espalier.config.yaml"), "utf8");
  // Normalized for the same reason the loader normalizes it: `./espalier/` and
  // `espalier` are one directory, and this is compared against a
  // repository-relative segment that carries neither decoration.
  const written = /^root:\s*(\S+)/m.exec(config)?.[1] ?? "espalier";
  const espalierRoot = path.posix.normalize(written).replace(/\/+$/, "");

  return walkFollowing(dir).filter((at) => {
    const top = at.split("/")[0]!;
    // The two configuration files and the espalier root are invisible
    // unconditionally, so listing them would be a column of nulls.
    return (
      !SCAFFOLDING.has(top) &&
      top !== "espalier.config.yaml" &&
      top !== ".espalierignore" &&
      top !== espalierRoot
    );
  });
}

function explainAll(dir: string, paths: string[]): Map<string, Answer> {
  const answers = new Map<string, Answer>();
  for (const at of paths) {
    const [line] = parseLines(run(dir, ["explain", at, "--format", "jsonl"]).stdout, `explain ${at}`);
    const rule = line?.["rule"];
    const ignoredBy = line?.["ignoredBy"];
    answers.set(at, {
      rule: typeof rule === "string" ? rule : null,
      ignoredBy: typeof ignoredBy === "string" ? ignoredBy : null,
    });
  }
  return answers;
}

function checkOwnership(expected: Record<string, string | null>, answers: Map<string, Answer>): void {
  // Hand-written, and kept alongside the derived check below because it is
  // written from the specification rather than from the implementation: it is
  // the one oracle here that cannot agree with a bug by construction.
  const actual: Record<string, string | null> = {};
  for (const [at, answer] of answers) actual[at] = answer.rule;

  assert.deepEqual(
    actual,
    expected,
    "ownership: every file in the fixture must appear, with no extras",
  );
}

/**
 * Every command must answer the same way about the same path.
 *
 * Nothing above this can see a disagreement. A fixture pins what one run
 * reports, and the bugs that have actually happened here were two runs
 * reporting different things about one file: `explain` calling a path owned
 * while `lint` never enumerated it, or the two walking a resolved directory
 * with different captures in hand. Both were invisible to every assertion in
 * the suite and to line coverage, which counts execution rather than agreement.
 *
 * So this asserts the relationships rather than the answers, and needs no
 * expectation written for it — which is why it runs on every fixture instead of
 * the ones somebody remembered to write a map for.
 */
async function checkAgreement(dir: string, paths: string[], answers: Map<string, Answer>): Promise<void> {
  await sweep(dir, "", paths, answers);
}

/**
 * One espalier's share of the sweep, then each of its children's.
 *
 * `explain` delegates to the nearest espalier at or above a path, so the answer
 * already in hand for `packages/api/index.ts` came from the espalier in
 * `packages/api`. Comparing it against the *parent* would be comparing two
 * different questions; the child is opened and asked its own.
 */
async function sweep(
  root: string,
  prefix: string,
  paths: string[],
  answers: Map<string, Answer>,
): Promise<void> {
  let repository;
  try {
    repository = await open(undefined, path.join(root, prefix));
  } catch {
    // A child that will not compile reports its failure and describes nothing.
    // The fixture asserting that failure is what pins it.
    return;
  }

  const under = prefix === "" ? paths : paths.filter((at) => at.startsWith(`${prefix}/`));
  const deferred: string[] = [];

  for (const at of under) {
    const relative = prefix === "" ? at : at.slice(prefix.length + 1);
    if (repository.children.some((child) => relative.startsWith(`${child}/`))) {
      deferred.push(at);
      continue;
    }

    const answer = answers.get(at)!;
    const excluded = repository.ungoverned(relative);
    const enumerated = repository.visibleSet.has(relative);

    // Claiming an owner for a path no run enumerated is the shape the symlink
    // hole had: `explain` walked the trie, `lint` walked the filesystem, and
    // nothing compared the two.
    if (answer.rule !== null) {
      assert.ok(enumerated, `${at}: explain says it is owned, lint never saw it`);
    }

    if (excluded !== null) {
      assert.equal(answer.ignoredBy, excluded, `${at}: explain disagrees about what excludes it`);
      assert.equal(answer.rule, null, `${at}: excluded, and explain still named an owner`);
      continue;
    }

    assert.ok(enumerated, `${at}: nothing excluded it and nothing enumerated it`);

    // The trie walk `explain` does and the one `lint` resolves ownership with
    // must land on the same rule, captures and all.
    const owner = repository.resolve(relative);
    assert.equal(
      answer.rule,
      isOwnership(owner) ? owner.rule.modulePath : null,
      `${at}: explain and lint resolve different owners`,
    );
  }

  // The prefix form walks the trie itself rather than resolving one path
  // through it, so asking it about a file would compare `resolve` with
  // `resolve`. Asking it about a directory is what catches a walk that loses
  // the captures on the way down: the node it fails to reach declares nothing,
  // and every rule that owns a file under it goes missing from the answer.
  const governed = under.filter((at) => {
    const relative = prefix === "" ? at : at.slice(prefix.length + 1);
    return !deferred.includes(at) && repository.visibleSet.has(relative);
  });

  for (const directory of directoriesOf(
    governed.map((at) => (prefix === "" ? at : at.slice(prefix.length + 1))),
  )) {
    const owners = new Set<string>();
    for (const at of governed) {
      const relative = prefix === "" ? at : at.slice(prefix.length + 1);
      if (directory !== "" && !relative.startsWith(`${directory}/`)) continue;
      const owner = repository.resolve(relative);
      if (isOwnership(owner)) owners.add(owner.rule.modulePath);
    }
    if (owners.size === 0) continue;

    const target = directory === "" ? "." : `${directory}/`;
    const at = prefix === "" ? target : path.join(prefix, target) + (directory === "" ? "/" : "");
    const [line] = parseLines(
      run(root, ["explain", at, "--format", "jsonl"]).stdout,
      `explain ${at}`,
    );
    const listed = new Set(
      ((line?.["rules"] as { rule?: unknown }[] | undefined) ?? [])
        .map((entry) => entry.rule)
        .filter((rule): rule is string => typeof rule === "string"),
    );

    for (const owner of owners) {
      assert.ok(
        listed.has(owner),
        `explain ${at}: does not declare ${owner}, which owns a file under it`,
      );
    }
  }

  for (const child of repository.children) {
    const at = prefix === "" ? child : `${prefix}/${child}`;
    await sweep(root, at, deferred, answers);
  }
}

function lintIn(dir: string, scratch: string, expected: Expected): void {
  const scoped = expected.args ?? [];
  const lint = run(scratch, ["lint", "--format", "jsonl", ...scoped], expected.env);
  const lines = parseLines(lint.stdout, "lint");

  assert.equal(
    lint.status,
    expected.exit,
    `exit code\nstdout:\n${lint.stdout}\nstderr:\n${lint.stderr}`,
  );

  if (expected.error !== undefined) {
    const failures = lines.filter((line) => line.kind === "failure");
    // A bare string is the common case and means the code alone. An object is
    // compared by the same partial rule as everything else, for a fixture that
    // needs to pin another field of the failure — which espalier reported it.
    const want =
      typeof expected.error === "string" ? { code: expected.error } : expected.error;
    assert.ok(
      failures.some((failure) => mismatch(failure, want, "failure") === null),
      `expected a failure matching ${JSON.stringify(want)}, got ${JSON.stringify(failures)}`,
    );
  }

  const problems = compareIssues(
    lines.filter((line) => line.kind === "issue"),
    expected.issues ?? [],
  );
  assert.ok(problems.length === 0, problems.join("\n"));

  if (expected.warnings !== undefined) {
    assert.deepEqual(
      lines.filter((line) => line.kind === "warning").map((line) => line["message"]),
      expected.warnings,
      "lint warnings",
    );
  }

  // What a person reads is a separate surface from what a machine parses, and a
  // format nobody pins is a format that drifts.
  if (expected.human !== undefined) {
    const shown = run(scratch, ["lint", ...scoped], expected.env);
    assert.equal(
      shown.stdout,
      readFileSync(path.join(dir, expected.human), "utf8"),
      `lint --format human differs from ${expected.human}`,
    );
  }

  // Some effects have no reporting channel — addon disposal happens after the
  // last issue is emitted and after the exit code is decided. A marker on
  // stderr is the only way to see that it happened at all.
  for (const fragment of expected.stderr ?? []) {
    assert.ok(
      lint.stderr.includes(fragment),
      `stderr should contain ${JSON.stringify(fragment)}, got:\n${lint.stderr}`,
    );
  }

  for (const [target, want] of Object.entries(expected.explain ?? {})) {
    const explain = run(scratch, ["explain", target, "--format", "jsonl"]);
    const objects = parseLines(explain.stdout, `explain ${target}`);
    assert.equal(
      objects.length,
      1,
      `explain ${target} should emit one object, got ${objects.length}\nstderr:\n${explain.stderr}`,
    );
    assert.equal(
      explain.status,
      want.exit,
      `explain ${target} exit code\nstdout:\n${explain.stdout}\nstderr:\n${explain.stderr}`,
    );
    const found = mismatch(objects[0], want.object, `explain[${target}]`);
    assert.equal(found, null, found ?? undefined);

    // The human layout is fixed by cli/explain/README.MD, so it is pinned the
    // same way build's documents are: byte for byte, against a file a reader
    // can diff.
    if (want.human !== undefined) {
      const human = run(scratch, ["explain", target]);
      assert.equal(
        human.stdout,
        readFileSync(path.join(dir, want.human), "utf8"),
        `explain ${target} --format human differs from ${want.human}`,
      );
    }
  }

  if (expected.again !== undefined) rerun(dir, scratch, expected.again, scoped);
}

/**
 * Changes the copy and lints it again. What the second run reports is the
 * whole assertion: a rule replayed from cache answers with what it said the
 * first time, and one whose inputs moved answers afresh. The environment is
 * the lever, because it is the one input a rule can read and the cache cannot
 * see — which is exactly what makes a skip visible in output that is
 * otherwise identical warm and cold.
 */
function rerun(dir: string, scratch: string, again: Rerun, scoped: string[]): void {
  if (again.apply !== undefined) {
    cpSync(path.join(dir, again.apply), scratch, { recursive: true, verbatimSymlinks: true });
  }
  for (const target of again.delete ?? []) {
    rmSync(path.join(scratch, target), { recursive: true, force: true });
  }

  const lint = run(scratch, ["lint", "--format", "jsonl", ...scoped], again.env);
  assert.equal(
    lint.status,
    again.exit,
    `again: exit code\nstdout:\n${lint.stdout}\nstderr:\n${lint.stderr}`,
  );

  const problems = compareIssues(
    parseLines(lint.stdout, "again").filter((line) => line.kind === "issue"),
    again.issues ?? [],
  );
  assert.ok(problems.length === 0, problems.map((problem) => `again: ${problem}`).join("\n"));
}

/**
 * Runs `lint` against a throwaway copy, for the reason `build` does: fixtures
 * are inputs and are never written into. The copy is verbatim rather than
 * scaffolding-filtered, because every fixture config ignores its own
 * scaffolding and removing it would change the file set under test.
 *
 * Goldens are still read from the fixture itself — they are what the run is
 * compared against, not part of the repository it runs on.
 */
function checkLint(dir: string, expected: Expected): void {
  const scratch = mkdtempSync(path.join(os.tmpdir(), "espalier-lint-"));
  try {
    cpSync(dir, scratch, { recursive: true, verbatimSymlinks: true });
    lintIn(dir, scratch, expected);
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

for (const name of fixtures) {
  test(name, async () => {
    const dir = path.join(fixturesDir, name);
    const expected = JSON.parse(
      readFileSync(path.join(dir, "expected.json"), "utf8"),
    ) as Expected;

    // A fixture asserts a lint run, a build run, or both. The harness runs
    // only what is asserted.
    if (expected.exit !== undefined) checkLint(dir, expected);

    // Every fixture whose espalier compiles is swept, whether or not it wrote
    // an ownership map. A fixture that fails before matching has nothing to
    // agree about.
    if (expected.exit !== 2 && expected.error === undefined && existsSync(path.join(dir, "espalier.config.yaml"))) {
      const paths = subject(dir);
      const answers = explainAll(dir, paths);
      if (expected.ownership !== undefined) checkOwnership(expected.ownership, answers);
      await checkAgreement(dir, paths, answers);
    } else if (expected.ownership !== undefined) {
      checkOwnership(expected.ownership, explainAll(dir, subject(dir)));
    }
    if (expected.build !== undefined) checkWrites(dir, "build", expected.build);
    if (expected.init !== undefined) checkWrites(dir, "init", expected.init);
    if (expected.adopt !== undefined) checkWrites(dir, "adopt", expected.adopt);
  });
}
