// The published package boundary. README.MD "Quick start".

import { spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import os from "node:os";
import path from "node:path";
import assert from "node:assert/strict";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..", "..");

interface PackedFile {
  path: string;
}

interface PackedPackage {
  filename: string;
  files: PackedFile[];
}

function run(command: string, args: string[], cwd: string) {
  const result = spawnSync(command, args, { cwd, encoding: "utf8" });
  if (result.error) throw result.error;
  return { status: result.status ?? -1, stdout: result.stdout, stderr: result.stderr };
}

function succeed(command: string, args: string[], cwd: string): string {
  const result = run(command, args, cwd);
  assert.equal(
    result.status,
    0,
    `${command} ${args.join(" ")} failed\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`,
  );
  return result.stdout;
}

test("the packed package installs and supports the quick start", () => {
  const scratch = mkdtempSync(path.join(os.tmpdir(), "espalier-package-"));
  const app = path.join(scratch, "app");
  mkdirSync(app);

  try {
    const packed = JSON.parse(
      succeed("npm", ["pack", "--ignore-scripts", "--pack-destination", scratch, "--json"], root),
    ) as PackedPackage[];
    assert.equal(packed.length, 1);
    const manifest = packed[0]!;
    const files = manifest.files.map((entry) => entry.path);

    assert.ok(files.includes("dist/src/cli.js"));
    assert.ok(files.includes("dist/src/api.js"));
    assert.ok(files.includes("ignores/_common.gitignore"));
    assert.ok(files.includes("ignores/javascript.gitignore"));
    assert.ok(!files.includes("ignores/AGENTS.MD"));
    assert.ok(files.filter((entry) => entry.startsWith("ignores/")).every((entry) => entry.endsWith(".gitignore")));

    writeFileSync(path.join(app, "package.json"), '{"name":"consumer","private":true,"type":"module"}\n');
    const metadata = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8")) as {
      dependencies?: Record<string, string>;
    };
    const dependencies = Object.keys(metadata.dependencies ?? {}).map((name) =>
      path.join(root, "node_modules", ...name.split("/")),
    );
    succeed(
      "npm",
      [
        "install",
        "--ignore-scripts",
        "--no-audit",
        "--no-fund",
        "--package-lock=false",
        path.join(scratch, manifest.filename),
        ...dependencies,
      ],
      app,
    );

    const bin = path.join(
      app,
      "node_modules",
      ".bin",
      process.platform === "win32" ? "espalier.cmd" : "espalier",
    );
    assert.ok(existsSync(bin));
    writeFileSync(path.join(app, ".gitignore"), "node_modules/\n");
    succeed(bin, ["init", "--lang", "javascript"], app);
    succeed(bin, ["build"], app);
    succeed(bin, ["lint"], app);
    assert.match(readFileSync(path.join(app, "AGENTS.MD"), "utf8"), /^<!-- generated by espalier/);

    succeed(
      process.execPath,
      [
        "--input-type=module",
        "--eval",
        'import { runAggregate, runRule } from "espalier"; if (typeof runRule !== "function" || typeof runAggregate !== "function") process.exit(1);',
      ],
      app,
    );
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
});
