// What counts as a file. docs/CONFIG.MD "What counts as a file".

import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { WALK_EXCLUSIONS } from "./defaults.js";
import { fail } from "./errors.js";

/**
 * The opening of the header `espalier build` writes into every file it
 * generates. Generated documentation is identified by provenance rather than by
 * path, because `build` distributes files through the tree.
 */
export const PROVENANCE = "<!-- generated by espalier";

/**
 * A root is git-backed when it holds a `.git` entry of its own. Deliberately
 * local rather than asking git: a directory nested inside some larger
 * repository is not thereby a repository, and asking git would answer about the
 * enclosing one — resolving every path against a root the config never named.
 */
export function isGitBacked(root: string): boolean {
  return existsSync(path.join(root, ".git"));
}

function fromGit(root: string): string[] {
  let output: string;
  try {
    output = execFileSync(
      "git",
      ["ls-files", "--cached", "--others", "--exclude-standard", "-z"],
      { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
    );
  } catch (cause) {
    fail("git_failed", `could not list files with git: ${(cause as Error).message}`);
  }
  return output.split("\0").filter((entry) => entry !== "");
}

function walk(root: string): string[] {
  const found: string[] = [];

  const descend = (absolute: string, prefix: string): void => {
    for (const entry of readdirSync(absolute, { withFileTypes: true })) {
      if (WALK_EXCLUSIONS.has(entry.name)) continue;
      const relative = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
      if (entry.isDirectory()) {
        descend(path.join(absolute, entry.name), relative);
      } else if (entry.isFile()) {
        found.push(relative);
      }
    }
  };

  descend(root, "");
  return found;
}

export function collectCandidates(root: string): string[] {
  const found = isGitBacked(root) ? fromGit(root) : walk(root);
  return [...new Set(found)].sort();
}

export function isGenerated(root: string, relativePath: string): boolean {
  try {
    const contents = readFileSync(path.join(root, relativePath), "utf8");
    return contents.startsWith(PROVENANCE);
  } catch {
    return false;
  }
}

/** Matches a repo-relative path against a `*` / `**` glob. */
export function matchGlob(pattern: string, target: string): boolean {
  let body = "";

  for (let i = 0; i < pattern.length; i += 1) {
    const char = pattern[i]!;
    if (char === "*") {
      if (pattern[i + 1] === "*") {
        const afterSlash = i === 0 || pattern[i - 1] === "/";
        const beforeSlash = pattern[i + 2] === "/";
        if (afterSlash && beforeSlash) {
          body += "(?:.*/)?";
          i += 2;
        } else {
          body += ".*";
          i += 1;
        }
      } else {
        body += "[^/]*";
      }
      continue;
    }
    body += /[.+?^${}()|[\]\\]/.test(char) ? `\\${char}` : char;
  }

  return new RegExp(`^${body}$`).test(target);
}
