// What counts as a file. docs/CONFIG.MD "What counts as a file".

import { readdirSync, readFileSync, statSync, type Dirent } from "node:fs";
import path from "node:path";
import { fail } from "./errors.js";
import { ignores, type IgnoreRule } from "./ignore.js";

/**
 * The opening of the header `espalier build` writes into every file it
 * generates. Generated documentation is identified by provenance rather than by
 * path, because `build` distributes files through the tree.
 */
export const PROVENANCE = "<!-- generated by espalier";

/**
 * What an entry is, and — for a directory — which directory it is.
 *
 * A symlink is not a kind of its own: what it points at decides, so the same
 * walk sees it as the file or the directory it names. docs/CONFIG.MD
 * "Symlinks". `id` is `dev:ino`, which is what makes a cycle visible, and is
 * read for every directory rather than only for links: a link is recognized by
 * arriving somewhere the walk has already been, and the place it arrives was
 * reached the ordinary way.
 */
export interface Entry {
  kind: "file" | "directory" | "other";
  id: string | null;
}

/**
 * Resolves an entry, failing on a path that cannot be read.
 *
 * A plain file is answered from the directory listing, which already knows: the
 * extra `stat` is paid only by directories, which are about to cost a `readdir`
 * anyway, and by links, which did not previously exist as far as this walk was
 * concerned.
 */
export function inspect(entry: Dirent, absolute: string, relativePath: string): Entry {
  if (!entry.isSymbolicLink() && !entry.isDirectory()) {
    return { kind: entry.isFile() ? "file" : "other", id: null };
  }

  let stats;
  try {
    stats = statSync(absolute);
  } catch (cause) {
    // A link pointing nowhere, or a target this process may not reach. Either
    // way the path cannot be checked, and what cannot be checked cannot be
    // pronounced correct. docs/CONFIG.MD "Symlinks".
    fail("unreadable_path", `${relativePath} could not be read: ${(cause as Error).message}`);
  }

  if (stats.isDirectory()) return { kind: "directory", id: `${stats.dev}:${stats.ino}` };
  return { kind: stats.isFile() ? "file" : "other", id: null };
}

/**
 * The kind of an entry, or null when it will not resolve.
 *
 * The tolerant counterpart of `inspect`, for the two commands that propose
 * rather than pronounce. `init` writing a starting `ignore` list and `adopt`
 * inferring a scaffold are suggestions their author edits, not verdicts about
 * the repository, and a link nothing can follow is not something to infer
 * from. Failing would also be a trap: `init` refusing to run is `init`
 * refusing to write the `ignore` entry that excuses the link.
 */
export function probe(entry: Dirent, absolute: string): Entry["kind"] | null {
  if (!entry.isSymbolicLink() && !entry.isDirectory()) {
    return entry.isFile() ? "file" : "other";
  }
  try {
    const stats = statSync(absolute);
    return stats.isDirectory() ? "directory" : stats.isFile() ? "file" : "other";
  } catch {
    return null;
  }
}

/** Lists a directory, failing rather than skipping when it will not open. */
export function readEntries(absolute: string, relativePath: string): Dirent[] {
  try {
    return readdirSync(absolute, { withFileTypes: true });
  } catch (cause) {
    fail(
      "unreadable_path",
      `${relativePath === "" ? "." : relativePath} could not be read: ${(cause as Error).message}`,
    );
  }
}

/** The identity of a directory that is known to be readable — the walk root. */
function identify(absolute: string): string {
  const stats = statSync(absolute);
  return `${stats.dev}:${stats.ino}`;
}

/**
 * Every file under `root`, minus whatever the ignore rules exclude.
 *
 * The rules are consulted on the way down rather than afterwards, so an ignored
 * directory costs one `readdir` instead of everything beneath it. That is the
 * only reason candidacy takes the rules at all, and it carries git's own
 * limitation with it: a negation cannot re-include something under a directory
 * that was never entered.
 *
 * `skip` is the espalier root, which is not entered for the same reason and a
 * stronger one. Everything inside it is invisible unconditionally, so walking it
 * could only produce paths to discard — and the cache lives there. "A cache that
 * cannot be used is not an error" (cli/lint/README.MD) has to survive a cache
 * directory this process cannot open, which it does not if the walk goes looking.
 */
export function collectCandidates(root: string, rules: IgnoreRule[], skip?: string): string[] {
  const found: string[] = [];
  // The directories on the way down from the root, by `dev:ino`. A link is a
  // cycle exactly when it lands on one of them, and seeding the root is what
  // makes a link straight back to it a cycle rather than a second repository.
  const ancestors = new Set<string>([identify(root)]);

  const descend = (absolute: string, prefix: string): void => {
    for (const entry of readEntries(absolute, prefix)) {
      const relative = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
      if (relative === skip) continue;
      const at = path.join(absolute, entry.name);

      // An ignored path is never read, and resolving a link is a read that can
      // fail. The rules are consulted first, under both interpretations: which
      // one applies is precisely what resolving would have answered, and a
      // broken link nobody can fix must stay excludable.
      if (entry.isSymbolicLink() && (ignores(rules, relative, true) || ignores(rules, relative))) {
        continue;
      }

      const resolved = inspect(entry, at, relative);

      if (resolved.kind === "directory") {
        if (ignores(rules, relative, true)) continue;
        // Only an ancestor is refused, not every directory reached twice.
        // Two links to one directory are two paths, and both of them exist —
        // reporting the file under whichever the walk happened to arrive by
        // first would make the answer depend on the order a `readdir` returned.
        // docs/CONFIG.MD "Symlinks".
        if (ancestors.has(resolved.id!)) continue;
        ancestors.add(resolved.id!);
        descend(at, relative);
        ancestors.delete(resolved.id!);
      } else if (resolved.kind === "file") {
        found.push(relative);
      }
    }
  };

  descend(root, "");
  return [...new Set(found)].sort();
}

/**
 * Whether `build` wrote this file. Provenance rather than path, because `build`
 * distributes documents through the tree.
 *
 * A file that will not open is not one this run wrote, which is the safe answer
 * and an unreachable one: the walk that produced this path opened its directory
 * a moment ago. Guarding the gap costs a branch.
 */
export function isGenerated(root: string, relativePath: string): boolean {
  try {
    const contents = readFileSync(path.join(root, relativePath), "utf8");
    return contents.startsWith(PROVENANCE);
  } catch {
    return false;
  }
}

/** Matches a repo-relative path against a `*` / `**` glob. */
export function matchGlob(pattern: string, target: string): boolean {
  let body = "";

  for (let i = 0; i < pattern.length; i += 1) {
    const char = pattern[i]!;
    if (char === "*") {
      if (pattern[i + 1] === "*") {
        const afterSlash = i === 0 || pattern[i - 1] === "/";
        const beforeSlash = pattern[i + 2] === "/";
        if (afterSlash && beforeSlash) {
          body += "(?:.*/)?";
          i += 2;
        } else {
          body += ".*";
          i += 1;
        }
      } else {
        body += "[^/]*";
      }
      continue;
    }
    body += /[.+?^${}()|[\]\\]/.test(char) ? `\\${char}` : char;
  }

  return new RegExp(`^${body}$`).test(target);
}
