// What counts as a file. docs/CONFIG.MD "What counts as a file".

import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { ignores, type IgnoreRule } from "./ignore.js";

/**
 * The opening of the header `espalier build` writes into every file it
 * generates. Generated documentation is identified by provenance rather than by
 * path, because `build` distributes files through the tree.
 */
export const PROVENANCE = "<!-- generated by espalier";

/**
 * Every file under `root`, minus whatever the ignore rules exclude.
 *
 * The rules are consulted on the way down rather than afterwards, so an ignored
 * directory costs one `readdir` instead of everything beneath it. That is the
 * only reason candidacy takes the rules at all, and it carries git's own
 * limitation with it: a negation cannot re-include something under a directory
 * that was never entered.
 */
export function collectCandidates(root: string, rules: IgnoreRule[]): string[] {
  const found: string[] = [];

  const descend = (absolute: string, prefix: string): void => {
    for (const entry of readdirSync(absolute, { withFileTypes: true })) {
      const relative = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
      if (entry.isDirectory()) {
        if (ignores(rules, relative, true)) continue;
        descend(path.join(absolute, entry.name), relative);
      } else if (entry.isFile()) {
        found.push(relative);
      }
    }
  };

  descend(root, "");
  return [...new Set(found)].sort();
}

export function isGenerated(root: string, relativePath: string): boolean {
  try {
    const contents = readFileSync(path.join(root, relativePath), "utf8");
    return contents.startsWith(PROVENANCE);
  } catch {
    return false;
  }
}

/** Matches a repo-relative path against a `*` / `**` glob. */
export function matchGlob(pattern: string, target: string): boolean {
  let body = "";

  for (let i = 0; i < pattern.length; i += 1) {
    const char = pattern[i]!;
    if (char === "*") {
      if (pattern[i + 1] === "*") {
        const afterSlash = i === 0 || pattern[i - 1] === "/";
        const beforeSlash = pattern[i + 2] === "/";
        if (afterSlash && beforeSlash) {
          body += "(?:.*/)?";
          i += 2;
        } else {
          body += ".*";
          i += 1;
        }
      } else {
        body += "[^/]*";
      }
      continue;
    }
    body += /[.+?^${}()|[\]\\]/.test(char) ? `\\${char}` : char;
  }

  return new RegExp(`^${body}$`).test(target);
}
