// Turning the espalier into documentation. docs/cli/build/README.MD "Rendering".
//
// Every generated byte is decided here. `build.ts` owns the filesystem; this
// file owns what goes in it, which is why it takes no paths and touches no
// disk — a renderer that could read a file could produce output that depends
// on something other than the espalier.

import type { Constraint, Espalier, NodeDoc, StructuralRule, TrieNode } from "./compile.js";
import { PROVENANCE } from "./files.js";
import { backrefNames, type Segment } from "./pattern.js";

export const AMENDING = `## Amending this structure

This file is generated from \`espalier/\`, and the structure it describes is not
yours to change. If the work does not fit — a file has nowhere legal to go, or a
rule is wrong for the task — YOU MUST stop and report the gap. YOU MUST NOT
widen a pattern, add a rule, or edit \`espalier/\` to make an error go away.
Deciding the shape of this project is the architect's job, and a task that
appears to require changing that shape is a task to hand back, not to unblock.`;

export const CHECKING = `## Checking your work

Run \`espalier lint\` before you finish. Every violation it reports arrives with
the rule text attached, so a failure tells you what to do and not only what is
wrong.`;

const WIDTH = 80;

/**
 * Extension aliases for the description `espalier` writes when a constraint
 * module does not export one. Deliberately short: a wrong guess is corrected by
 * exporting a `description`, and a long table would still miss the next project.
 */
const ALIASES: Record<string, string> = {
  ts: "TypeScript",
  tsx: "TypeScript",
  js: "JavaScript",
  jsx: "JavaScript",
  mjs: "JavaScript",
  cjs: "JavaScript",
  py: "Python",
  go: "Go",
  rs: "Rust",
  java: "Java",
  rb: "Ruby",
  php: "PHP",
  cs: "C#",
  swift: "Swift",
  kt: "Kotlin",
  css: "CSS",
  scss: "Sass",
  html: "HTML",
  json: "JSON",
  yaml: "YAML",
  yml: "YAML",
  md: "Markdown",
  sql: "SQL",
  sh: "shell",
};

/**
 * Greedy wrap, for text `espalier` composed. Text an author wrote is copied
 * verbatim and never passed through here — reflowing someone's markdown is how
 * a tool mangles a table.
 */
export function wrap(text: string, width = WIDTH): string {
  const lines: string[] = [];
  let current = "";

  for (const word of text.split(/\s+/).filter((entry) => entry !== "")) {
    const candidate = current === "" ? word : `${current} ${word}`;
    if (candidate.length <= width) {
      current = candidate;
    } else {
      if (current !== "") lines.push(current);
      current = word;
    }
  }

  if (current !== "") lines.push(current);
  return lines.join("\n");
}

/** `a`, `a and b`, `a, b and c`. */
function list(entries: string[]): string {
  if (entries.length <= 1) return entries[0] ?? "";
  return `${entries.slice(0, -1).join(", ")} and ${entries[entries.length - 1]!}`;
}

function under(prefix: string, name: string): string {
  return prefix === "" ? name : `${prefix}/${name}`;
}

function isDirectory(node: TrieNode): boolean {
  return node.children.size > 0;
}

/** Directories before files, then static before dynamic, then lexicographic. */
function ordered(node: TrieNode): TrieNode[] {
  return [...node.children.values()].sort((left, right) => {
    const kind = Number(!isDirectory(left)) - Number(!isDirectory(right));
    if (kind !== 0) return kind;
    // static, then resolved, then dynamic — the same specificity order the
    // matcher uses. docs/cli/build/README.MD "Generation".
    const tier = (node: TrieNode): number =>
      node.segment.dynamic ? 2 : node.segment.resolved ? 1 : 0;
    const specificity = tier(left) - tier(right);
    if (specificity !== 0) return specificity;
    return left.display < right.display ? -1 : left.display > right.display ? 1 : 0;
  });
}

interface Visit {
  node: TrieNode;
  depth: number;
  /** Path relative to the node the walk started from. */
  at: string;
}

function* subtree(node: TrieNode, depth = 0, at = ""): Generator<Visit> {
  for (const child of ordered(node)) {
    const path = under(at, child.display);
    yield { node: child, depth, at: path };
    if (isDirectory(child)) yield* subtree(child, depth + 1, path);
  }
}

/**
 * Static leaves reachable through static directories only, in map order,
 * split by whether the espalier insists they exist. These are the files an
 * agent is being told about — either always, when the walk starts at a
 * placement point, or per instance, when it starts at a dynamic directory.
 */
export function leavesUnder(node: TrieNode, at = ""): { required: string[]; optional: string[] } {
  const required: string[] = [];
  const optional: string[] = [];

  for (const child of ordered(node)) {
    if (child.segment.dynamic) continue;
    const path = under(at, child.display);
    if (child.rule !== null) (child.rule.module.optional ? optional : required).push(path);
    if (isDirectory(child)) {
      const inside = leavesUnder(child, path);
      required.push(...inside.required);
      optional.push(...inside.optional);
    }
  }

  return { required, optional };
}

export function requiredUnder(node: TrieNode, at = ""): string[] {
  return leavesUnder(node, at).required;
}

/** The longest static prefix of a constraint's directory path. */
function staticPrefix(segments: Segment[]): string {
  const kept: string[] = [];
  for (const segment of segments) {
    if (segment.dynamic) break;
    kept.push(segment.source);
  }
  return kept.join("/");
}

type Section =
  | { kind: "rule"; at: string; rule: StructuralRule }
  | { kind: "directory"; at: string; doc: NodeDoc };

export interface Placement {
  /** Repository-relative directory, `""` for the root. */
  at: string;
  /** Null when nothing structural is declared here — a constraint-only point. */
  node: TrieNode | null;
  doc: NodeDoc | null;
  /** In map order. */
  sections: Section[];
  constraints: Constraint[];
}

/**
 * Walks the static spine for placement points and assigns every rule to the
 * longest static prefix of its directory. Sections are pushed during the walk,
 * which is already in map order, so no second sort is needed.
 */
export function plan(espalier: Espalier): Placement[] {
  const points = new Map<string, Placement>();

  const ensure = (at: string, node: TrieNode | null): Placement => {
    let found = points.get(at);
    if (found === undefined) {
      found = { at, node, doc: espalier.nodes.get(at) ?? null, sections: [], constraints: [] };
      points.set(at, found);
    } else if (found.node === null) {
      // Unreachable today: the only placements created with a null node are a
      // constraint's, and those are made after the walk, so nothing follows to
      // supply one. Kept because "first mention wins, later mention fills in"
      // is the rule this function is expressing, and losing it would make the
      // order of two calls matter silently.
      found.node = node;
    }
    return found;
  };

  ensure("", espalier.root);

  const walk = (node: TrieNode, at: string, point: string, spine: boolean): void => {
    for (const child of ordered(node)) {
      const path = under(at, child.display);
      const directory = isDirectory(child);
      const onSpine = spine && directory && !child.segment.dynamic;

      if (child.rule !== null) {
        ensure(point, null).sections.push({ kind: "rule", at: path, rule: child.rule });
      }

      if (!directory) continue;

      const doc = espalier.nodes.get(path) ?? null;

      if (onSpine) {
        ensure(path, child);
      } else if (doc !== null && doc.body !== "") {
        // A dynamic directory is never a placement point, so its prose has
        // nowhere of its own to go.
        ensure(point, null).sections.push({ kind: "directory", at: path, doc });
      }

      walk(child, path, onSpine ? path : point, onSpine);
    }
  };

  walk(espalier.root, "", "", true);

  for (const constraint of espalier.constraints) {
    const point = ensure(staticPrefix(constraint.directory), null);
    if (!point.constraints.some((other) => other.modulePath === constraint.modulePath)) {
      point.constraints.push(constraint);
    }
  }

  // An intermediate directory whose content all lives deeper produces no file.
  // The root is never dropped: it alone carries the map of the whole repository
  // and the instruction to run `lint`.
  const kept = [...points.values()].filter(
    (point) =>
      point.at === "" ||
      point.doc !== null ||
      point.sections.length > 0 ||
      point.constraints.length > 0,
  );

  return kept.sort((left, right) => (left.at < right.at ? -1 : left.at > right.at ? 1 : 0));
}

/**
 * What one map line says after its name. Each suffix is true of the line it
 * sits on and of nothing else, so a reader never has to work out which
 * directory or which depth is being talked about.
 * docs/cli/build/README.MD "Suffixes".
 */
function suffixes(node: TrieNode): string[] {
  const marks: string[] = [];

  // Named leaves only. A dynamic leaf has no name to require, and `any number,
  // any name` already says zero or more; a directory exists exactly when the
  // files inside it do, so requiring one would restate them or claim an empty
  // directory satisfies something.
  if (!isDirectory(node) && !node.segment.dynamic) {
    marks.push(node.rule?.module.optional === true ? "optional" : "required");
  }

  if (node.segment.dynamic) marks.push("any number, any name");

  // What the capture holds, not what the segment was: under
  // `[provider]-provider/`, `{provider}Impl.ts` is `stripeImpl.ts`, and "the
  // same name as the directory" would be wrong.
  for (const name of backrefNames(node.segment)) {
    marks.push(`{${name}} repeats what [${name}] matched`);
  }

  return marks;
}

interface MapRow {
  /** Branch characters and name. */
  line: string;
  /** What a continuation line hangs under: the branches, no name. */
  under: string;
  /** The branches a guide row below this line carries, already trimmed. */
  guide: string;
  text: string | null;
}

function renderMap(espalier: Espalier, point: Placement): string | null {
  if (point.node === null) return null;

  const rows: MapRow[] = [];

  const walk = (node: TrieNode, at: string, bars: string): void => {
    const children = ordered(node);

    children.forEach((child, index) => {
      const last = index === children.length - 1;
      const path = under(at, child.display);
      const directory = isDirectory(child);
      const inside = directory ? ordered(child) : [];

      // Where a continuation of this line hangs: the branch this entry sits on
      // stays open only while a sibling is still to come.
      const beneath = bars + (last ? "   " : "│  ");

      const description = directory
        ? (espalier.nodes.get(under(point.at, path))?.description ?? null)
        : (child.rule?.module.description ?? null);
      const marks = suffixes(child);
      const text = [description, ...marks].filter((entry) => entry !== null).join(", ");

      rows.push({
        line: bars + (last ? "└─ " : "├─ ") + child.display + (directory ? "/" : ""),
        under: beneath,
        // A directory's guide row descends one level, to the branch its own
        // children hang from. docs/cli/build/README.MD "The map".
        guide: (directory ? beneath + (inside.length > 1 ? "│" : "") : beneath).trimEnd(),
        text: text === "" ? null : text,
      });

      if (directory) walk(child, path, beneath);
    });
  };

  walk(point.node, "", "");

  if (rows.length === 0) return null;

  // Two spaces after the longest rendered line, counting the branch characters
  // and not the four spaces of the code block, which are added to every line
  // afterwards and so cannot change the alignment.
  const column = Math.max(...rows.map((row) => row.line.length)) + 2;
  const width = WIDTH - 4 - column;

  const lines: string[] = [];

  rows.forEach((row, index) => {
    if (row.text === null) {
      lines.push(`    ${row.line}`);
    } else {
      const [first, ...rest] = wrap(row.text, width).split("\n");
      lines.push(`    ${row.line.padEnd(column)}${first}`);
      for (const piece of rest) lines.push(`    ${row.under.padEnd(column)}${piece}`);
    }

    // A guide row wherever text is involved: a wrapped description otherwise
    // leaves a reader deciding whether the line below continues it or begins a
    // new entry. Two silent entries have no thread to lose.
    const next = rows[index + 1];
    if (next !== undefined && (row.text !== null || next.text !== null)) {
      lines.push(`    ${row.guide}`.trimEnd());
    }
  });

  return lines.join("\n");
}

/**
 * Which placement point names each child espalier: the deepest one above it.
 * Exactly one document names each, and it is the one whose closed set would
 * otherwise have covered the directory.
 * docs/cli/build/README.MD "Governed elsewhere".
 */
export function assignChildren(points: Placement[], children: string[]): Map<string, string[]> {
  const assigned = new Map<string, string[]>();

  for (const child of children) {
    let deepest = "";
    for (const point of points) {
      if (point.at === "") continue;
      if (child === point.at || child.startsWith(`${point.at}/`)) {
        if (point.at.length > deepest.length) deepest = point.at;
      }
    }
    const found = assigned.get(deepest);
    if (found === undefined) assigned.set(deepest, [child]);
    else found.push(child);
  }

  return assigned;
}

/**
 * What the closed set above defers to. A reader who can see a directory the
 * document does not describe, under a sentence saying nothing else may exist
 * here, is reading a lie — so the sentence defers instead, and this is where it
 * defers to.
 *
 * It names the children and stops. What they contain is not this espalier's to
 * summarize — a copy of somebody else's rules is a second source of truth that
 * goes stale silently — so the reader is sent to the directory instead.
 */
function renderChildren(at: string, children: string[], level: number): string[] {
  if (children.length === 0) return [];

  const prefix = at === "" ? "" : `${at}/`;
  const names = children
    .map((child) => `${child.slice(prefix.length)}/`)
    .sort((left, right) => (left < right ? -1 : left > right ? 1 : 0));

  const column = Math.max(...names.map((name) => name.length)) + 2;
  const rows = names.map((name) => `    ${name.padEnd(column)}has an espalier of its own`);

  return [
    `${"#".repeat(level)} Governed elsewhere`,
    rows.join("\n"),
    names.length === 1
      ? "Read the documentation inside it."
      : "Read the documentation inside each one.",
  ];
}

/** One excluded entry in a directory, and why it is excluded. */
export interface Excluded {
  /** Name as the directory lists it, with a trailing `/` for a directory. */
  name: string;
  /** The comment introducing the entry that excluded it, or null when none did. */
  reason: string | null;
}

/**
 * The other half of what makes the closed-set sentence true.
 *
 * `Governed elsewhere` names the directories another espalier describes; this
 * names the paths no espalier describes at all, so that between them every
 * entry a reader can see is accounted for by name. A closed set that ends in
 * *apart from* is not closed, and a reader who can see `package.json` sitting
 * beside one reads the whole paragraph as approximate.
 *
 * Reasons are quoted from `.espalierignore` and never invented: `espalier` has
 * patterns, not intent, and cannot tell an exclusion that will never have a
 * rule from one that does not have a rule yet.
 * docs/cli/build/README.MD "Not described here".
 */
function renderExcluded(entries: Excluded[], level: number): string[] {
  if (entries.length === 0) return [];

  // Grouped by reason, then by name within a group, and the entries nobody gave
  // a reason last. Sorting by name alone would scatter a group across the
  // section and leave the shared line landing wherever the alphabet put it.
  const sorted = [...entries].sort((left, right) => {
    const first = left.reason ?? "\uffff";
    const second = right.reason ?? "\uffff";
    if (first !== second) return first < second ? -1 : 1;
    return left.name < right.name ? -1 : left.name > right.name ? 1 : 0;
  });
  const column = Math.max(...sorted.map((entry) => entry.name.length)) + 2;

  const rows: string[] = [];
  for (const [index, entry] of sorted.entries()) {
    // Entries sharing a comment share it, carried on the first of them, so a
    // group written as one thought reads as one rather than as a refrain.
    const repeated = index > 0 && entry.reason !== null && entry.reason === sorted[index - 1]!.reason;
    const reason = repeated ? "" : (entry.reason ?? "");
    if (reason === "") {
      rows.push(`    ${entry.name}`);
      continue;
    }
    // Wrapped into the column rather than left to run past it. A map line is
    // never wrapped because an alignment column that survived a wrap would not
    // be one; here the alignment is what the continuation lines hang from.
    const indent = " ".repeat(4 + column);
    const [first, ...rest] = wrap(reason, WIDTH - indent.length).split("\n");
    rows.push(`    ${entry.name.padEnd(column)}${first}`);
    for (const line of rest) rows.push(`${indent}${line}`);
  }

  return [
    `${"#".repeat(level)} Not described here`,
    rows.join("\n"),
    "Nothing above describes these, so nothing here tells you how to write them. " +
      "That makes them a poor place to put work that belongs in the list above: a file " +
      "with nowhere legal to go is a gap to report, not one to route around.",
  ];
}

/**
 * What `explain` answers a directory prefix with, as one unwrapped string: the
 * same subtree the generated map covers, said in prose, because a terminal
 * answering one query is not the place for a drawing of the whole subtree. It
 * ends on `closedSet`, which is the sentence `build` writes — so the one claim
 * both make is made once. docs/cli/explain/README.MD "A prefix".
 */
export function cardinality(node: TrieNode, at: string, defers = false): string {
  const sentences: string[] = [];
  const { required, optional } = leavesUnder(node);
  if (required.length > 0) {
    sentences.push(`${list(required)} ${required.length === 1 ? "is" : "are"} required.`);
  }
  // Its own sentence rather than a qualifier inside the first: the two are
  // addressed to the same reader for opposite purposes, one being what an
  // agent must produce and the other what it may.
  // docs/cli/explain/README.MD "A prefix".
  if (optional.length > 0) {
    sentences.push(`${list(optional)} ${optional.length === 1 ? "is" : "are"} optional.`);
  }

  for (const visit of subtree(node)) {
    if (!visit.node.segment.dynamic) continue;

    if (isDirectory(visit.node)) {
      sentences.push(`Zero or more \`${visit.at}/\` directories may exist.`);
      const inside = leavesUnder(visit.node);
      if (inside.required.length > 0) {
        sentences.push(
          `For each one that does, ${list(inside.required)} ${inside.required.length === 1 ? "is" : "are"} required.`,
        );
      }
      if (inside.optional.length > 0) {
        sentences.push(`Each one may also have ${list(inside.optional)}.`);
      }
    } else {
      sentences.push(`Zero or more files matching \`${visit.at}\` may exist.`);
    }
  }

  sentences.push(closedSet(at, defers));

  return sentences.join(" ");
}

/**
 * The sentence the map ends on, and the whole of what `build` writes under it.
 * What must exist, what may, and what repeats what are marked on the lines
 * they belong to; a paragraph restating them below would be a second
 * description of one subtree. docs/cli/build/README.MD "The closed set".
 */
export function closedSet(at: string, defers: boolean): string {
  // No path to print at an espalier's own root — it would be `under .` — so the
  // sentence anchors on the file's location instead. A document cannot know
  // where it sits in an outer tree, and in a package "the repository root" is
  // wrong on both counts.
  const where = at === "" ? "this directory" : `${at}/`;
  // Where a child espalier falls inside the closed set, it defers rather than
  // stating something the reader can see is untrue — listing them after an
  // absolute sentence would not retract it. Stated in general rather than by
  // name, because every document whose subtree covers a child has to defer,
  // while only the deepest one above it names them. "already" is load-bearing:
  // this is an exception for the directories that have one, not a licence to
  // create another.
  const except = defers ? ", apart from the directories that already have an espalier of their own" : "";
  return `Nothing else may exist under ${where}${except}.`;
}

function renderClosedSet(point: Placement, covered: boolean): string | null {
  if (point.node === null) return null;
  return wrap(closedSet(point.at, covered));
}

/** `**​/*.ts` and `**​/*.tsx` → "applies to TypeScript files throughout the project". */
function describeConstraint(constraint: Constraint, extensions: string[]): string {
  if (constraint.module.description !== null) return constraint.module.description;

  const named = [...new Set(extensions.map((entry) => ALIASES[entry] ?? `.${entry}`))];
  const where = staticPrefix(constraint.directory);
  return `applies to ${list(named)} files ${where === "" ? "throughout the project" : `under ${where}/`}`;
}

/**
 * One entry per constraint module. `compile` produces a `Constraint` per
 * extension, because matching wants them separate; every reader wants them
 * back together.
 */
export interface ConstraintGroup {
  name: string;
  /** Espalier-relative module path. */
  rule: string;
  patterns: string[];
  description: string;
  ruleText: string;
  example: string | null;
  exampleSource: string | null;
  /** The longest static prefix of the directory the constraint applies under. */
  prefix: string;
  members: Constraint[];
}

export function constraintGroups(espalier: Espalier): ConstraintGroup[] {
  const grouped = new Map<string, Constraint[]>();

  for (const constraint of espalier.constraints) {
    const bucket = grouped.get(constraint.modulePath);
    if (bucket === undefined) grouped.set(constraint.modulePath, [constraint]);
    else bucket.push(constraint);
  }

  return [...grouped.values()].map((members) => {
    const first = members[0]!;
    return {
      name: first.name,
      rule: first.modulePath,
      patterns: members.map((entry) => entry.pattern),
      description: describeConstraint(
        first,
        members.map((entry) => entry.extension),
      ),
      ruleText: first.module.rule.trim(),
      example: first.module.example,
      exampleSource: first.module.exampleSource,
      prefix: staticPrefix(first.directory),
      members,
    };
  });
}

export { isDirectory, subtree };

function renderSections(espalier: Espalier, point: Placement, level: number): string[] {
  const hashes = "#".repeat(level);
  const blocks: string[] = [];

  for (const section of point.sections) {
    if (section.kind === "directory") {
      const heading = section.doc.description === null ? "" : ` — ${section.doc.description}`;
      blocks.push(`${hashes} ${section.at}/${heading}`, section.doc.body);
      continue;
    }

    const { module } = section.rule;
    const body: string[] = [];

    if (module.rule.trim() !== "") body.push(module.rule.trim());

    // A path reads as one line; source gets a fence, however many lines it has.
    // docs/cli/build/README.MD "Rule sections".
    if (module.example !== null) body.push(`Example: ${module.example}`);
    if (module.exampleSource !== null) {
      body.push(`Example:\n\n\`\`\`\n${module.exampleSource.trim()}\n\`\`\``);
    }

    // A section with nothing to say is omitted entirely, along with its
    // heading. docs/cli/build/README.MD "Rendering". `adopt` writes an empty
    // `rule` as a TODO, so a freshly adopted project hits this on every node.
    if (body.length === 0) continue;

    const heading = module.description === null ? "" : ` — ${module.description}`;
    blocks.push(`${hashes} ${section.at}${heading}`, ...body);
  }

  if (point.constraints.length > 0) {
    blocks.push(`${hashes} Constraints`);
    const groups = constraintGroups(espalier);

    for (const constraint of point.constraints) {
      const group = groups.find((entry) => entry.rule === constraint.modulePath)!;
      blocks.push(
        `${"#".repeat(level + 1)} ${group.name} — ${group.description}`,
        `Applies to: ${group.patterns.map((pattern) => `\`${pattern}\``).join(", ")}`,
        group.ruleText,
      );
    }
  }

  return blocks;
}

function marker(espalierRoot: string, at: string): string {
  const source = at === "" ? espalierRoot : `${espalierRoot}/${at}`;
  return `${PROVENANCE} — do not edit — source: ${source} -->`;
}

/** The body every document shares: prose, structure, sections. */
/** Whether any child espalier falls inside this placement point's closed set. */
function covers(at: string, children: string[]): boolean {
  return children.some((child) => at === "" || child === at || child.startsWith(`${at}/`));
}

function core(
  espalier: Espalier,
  point: Placement,
  level: number,
  named: string[],
  all: string[],
  excluded: Excluded[],
): string[] {
  const blocks: string[] = [];

  if (point.doc !== null && point.doc.body !== "") blocks.push(point.doc.body);

  const map = renderMap(espalier, point);
  const closed = renderClosedSet(point, covers(point.at, all));

  if (map !== null) {
    blocks.push(`${"#".repeat(level)} Structure`, map);
    if (closed !== null) blocks.push(closed);
  }

  blocks.push(...renderChildren(point.at, named, level));
  blocks.push(...renderExcluded(excluded, level));
  blocks.push(...renderSections(espalier, point, level));
  return blocks;
}

export function renderDistributed(
  espalier: Espalier,
  point: Placement,
  espalierRoot: string,
  named: string[] = [],
  all: string[] = named,
  excluded: Excluded[] = [],
): string {
  const blocks = [marker(espalierRoot, point.at), ...core(espalier, point, 2, named, all, excluded)];
  if (point.at === "") blocks.push(CHECKING);
  blocks.push(AMENDING);
  return `${blocks.join("\n\n")}\n`;
}

/**
 * One document at the root, with every other placement point folded into it a
 * heading level down. There is one map and one closed-set sentence, because
 * the root's were always the whole repository, and one amendment instruction,
 * because there is one file.
 */
export function renderInline(
  espalier: Espalier,
  points: Placement[],
  espalierRoot: string,
  children: string[] = [],
  excluded: Map<string, Excluded[]> = new Map(),
): string {
  const root = points.find((point) => point.at === "")!;
  const assigned = assignChildren(points, children);
  const blocks = [
    marker(espalierRoot, ""),
    ...core(espalier, root, 2, assigned.get("") ?? [], children, excluded.get("") ?? []),
  ];

  for (const point of points) {
    if (point.at === "") continue;
    // Prose and rule sections only. The root's map and closed-set sentence
    // cover the whole repository already, and both are written relative to the
    // point that produced them — folded in, they would state one rule several
    // times over in words that differ every time.
    // docs/cli/build/README.MD "`--inline`".
    const inside = assigned.get(point.at) ?? [];
    const body: string[] = [];
    if (point.doc !== null && point.doc.body !== "") body.push(point.doc.body);
    body.push(...renderChildren(point.at, inside, 3));
    body.push(...renderSections(espalier, point, 3));
    // A point exists because it has a document or rules of its own, so this is
    // all but unreachable — a description with an empty body and nothing placed
    // here. A bare heading is still not written.
    if (body.length === 0) continue;

    const heading = point.doc?.description == null ? "" : ` — ${point.doc.description}`;
    blocks.push(`## ${point.at}/${heading}`, ...body);
  }

  blocks.push(CHECKING, AMENDING);
  return `${blocks.join("\n\n")}\n`;
}
